# Generated by Django 5.1.6 on 2025-03-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stpapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('company', models.CharField(max_length=80, verbose_name='Название компании')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
                ('data_posted', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
        ),
    ]
